### ISSUE TITLE
QNAP 212P3安装问题

### ISSUE THREAD

**Issue by yuhw2001** [leonismoe/docker-images#1]
Arm64 处理器
QNAP威联通的containerstation直接安装，配置如图：
![2021-03-21_140525](https://user-images.githubusercontent.com/19515502/111895571-89dd5c80-8a4e-11eb-91f7-f9c5db9c6e4b.jpg)
报错如图：
![2021-03-21_140257](https://user-images.githubusercontent.com/19515502/111895577-92359780-8a4e-11eb-851c-207ca5ba1e7d.jpg)

因为非IT人士，还请大神指点一下，如何解决。谢谢！

**Comment by yuhw2001** [comment]
解决办法找到了：
https://maronyea.me/restless/131/
再次留言一下，帮助后来人，谢谢。

**Comment by leonismoe** [comment]
Please check your `server_addr`, frpc uses it to communicate with frps server, so it can't be `127.0.0.1`.

As for the docker network, `host` and `bridge` don't matter, you just need to make sure the frpc container can access the services you needed.
